In [21]:
import pandas as pd 
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt 
import seaborn as sns

In [22]:
path = 'data/products_all_brands.csv' 
df = pd.read_csv(path) 
df.head()

,product_name,product_id,beauty_point_earned,price_range,price_by_combinations,url,active_date,default_category,categories,rating_types_str,average_rating,total_reviews,average_rating_by_types,total_recommended_count,total_repurchase_maybe_count,total_repurchase_no_count,total_repurchase_yes_count,total_in_wishlist
0,MULTI EYE COLOR PALETTE,97802,130,Rp 555.000 - Rp 687.000,NaN,https://www.sociolla.com/eyeshadow/69460-phan-...,2022-10-03T03:30:06.681Z,Eyeshadow,Makeup; Eyes; Eyeshadow,is_star_long_wear;is_star_packaging;is_star_pi...,4.920000,5,"""star_long_wear"": 5; ""star_packaging"": 4.8; ""s...",5,0,0,5,717
1,VELVET LIP TINT,97810,50,Rp 264.000,NaN,https://www.sociolla.com/lip-cream/69468-son-k...,2022-10-03T03:02:40.340Z,Lip Cream,Makeup; Lips; Lip Cream,is_star_long_wear;is_star_packaging;is_star_pi...,4.576190,42,"""star_long_wear"": 4.309523809523809; ""star_pac...",42,10,2,30,682
2,LIP COLOR,97822,60,Rp 317.000,NaN,https://www.sociolla.com/lip-matte/69480-son-t...,2023-05-30T09:49:15.158Z,Lipstick,Makeup; Lips; Lipstick,is_star_long_wear;is_star_packaging;is_star_pi...,0.000000,0,NaN,0,0,0,0,173
3,MINI MULTI EYE COLOR PALETTE,97833,80,Rp 423.000,NaN,https://www.sociolla.com/eyeshadow/69491-phan-...,2022-10-03T03:27:01.334Z,Eyeshadow,Makeup; Eyes; Eyeshadow,is_star_long_wear;is_star_packaging;is_star_pi...,4.883333,6,"""star_long_wear"": 4.916666666666667; ""star_pac...",12,1,0,11,257
4,FACE BLUSH,97801,60,Rp 300.000,NaN,https://www.sociolla.com/blush/69459-phan-ma-h...,2022-10-03T03:22:26.610Z,Blush,Makeup; Face; Blush,is_star_long_wear;is_star_packaging;is_star_pi...,4.858824,13,"""star_long_wear"": 4.9411764705882355; ""star_pa...",17,2,0,15,387

In [23]:
path = 'data/products_all_brands.csv'
df = pd.read_csv(path , index_col=['product_id'])
df.head()

,product_name,beauty_point_earned,price_range,price_by_combinations,url,active_date,default_category,categories,rating_types_str,average_rating,total_reviews,average_rating_by_types,total_recommended_count,total_repurchase_maybe_count,total_repurchase_no_count,total_repurchase_yes_count,total_in_wishlist
product_id,,,,,,,,,,,,,,,,,
97802,MULTI EYE COLOR PALETTE,130,Rp 555.000 - Rp 687.000,NaN,https://www.sociolla.com/eyeshadow/69460-phan-...,2022-10-03T03:30:06.681Z,Eyeshadow,Makeup; Eyes; Eyeshadow,is_star_long_wear;is_star_packaging;is_star_pi...,4.920000,5,"""star_long_wear"": 5; ""star_packaging"": 4.8; ""s...",5,0,0,5,717
97810,VELVET LIP TINT,50,Rp 264.000,NaN,https://www.sociolla.com/lip-cream/69468-son-k...,2022-10-03T03:02:40.340Z,Lip Cream,Makeup; Lips; Lip Cream,is_star_long_wear;is_star_packaging;is_star_pi...,4.576190,42,"""star_long_wear"": 4.309523809523809; ""star_pac...",42,10,2,30,682
97822,LIP COLOR,60,Rp 317.000,NaN,https://www.sociolla.com/lip-matte/69480-son-t...,2023-05-30T09:49:15.158Z,Lipstick,Makeup; Lips; Lipstick,is_star_long_wear;is_star_packaging;is_star_pi...,0.000000,0,NaN,0,0,0,0,173
97833,MINI MULTI EYE COLOR PALETTE,80,Rp 423.000,NaN,https://www.sociolla.com/eyeshadow/69491-phan-...,2022-10-03T03:27:01.334Z,Eyeshadow,Makeup; Eyes; Eyeshadow,is_star_long_wear;is_star_packaging;is_star_pi...,4.883333,6,"""star_long_wear"": 4.916666666666667; ""star_pac...",12,1,0,11,257
97801,FACE BLUSH,60,Rp 300.000,NaN,https://www.sociolla.com/blush/69459-phan-ma-h...,2022-10-03T03:22:26.610Z,Blush,Makeup; Face; Blush,is_star_long_wear;is_star_packaging;is_star_pi...,4.858824,13,"""star_long_wear"": 4.9411764705882355; ""star_pa...",17,2,0,15,387

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7636 entries, 97802 to 64153
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   product_name                  7636 non-null   object
 1   beauty_point_earned           7636 non-null   int64
 2   price_range                   7636 non-null   object
 3   price_by_combinations         4087 non-null   object
 4   url                           7636 non-null   object
 5   active_date                   5534 non-null   object
 6   default_category              7636 non-null   object
 7   categories                    7632 non-null   object
 8   rating_types_str              7561 non-null   object
 9   average_rating                7636 non-null   float64
 10  total_reviews                 7636 non-null   int64
 11  average_rating_by_types       5790 non-null   object
 12  total_recommended_count       7636 non-null   int64
 13  total_repurchase_maybe_count  7636 non-null   int64
 14  total_repurchase_no_count     7636 non-null   int64
 15  total_repurchase_yes_count    7636 non-null   int64
 16  total_in_wishlist             7636 non-null   int64
dtypes: float64(1), int64(7), object(9)
memory usage: 1.0+ MB

In [25]:
df.drop(columns='price_by_combinations',inplace=True)

In [27]:
df.drop(columns='url',inplace=True)

In [29]:
df.drop(columns='active_date',inplace=True)

In [31]:
df.drop(columns='rating_types_str',inplace=True)

In [32]:
df.drop(columns='average_rating_by_types',inplace=True)

In [33]:
df

,product_name,beauty_point_earned,price_range,default_category,categories,average_rating,total_reviews,total_recommended_count,total_repurchase_maybe_count,total_repurchase_no_count,total_repurchase_yes_count,total_in_wishlist
product_id,,,,,,,,,,,,
97802,MULTI EYE COLOR PALETTE,130,Rp 555.000 - Rp 687.000,Eyeshadow,Makeup; Eyes; Eyeshadow,4.920000,5,5,0,0,5,717
97810,VELVET LIP TINT,50,Rp 264.000,Lip Cream,Makeup; Lips; Lip Cream,4.576190,42,42,10,2,30,682
97822,LIP COLOR,60,Rp 317.000,Lipstick,Makeup; Lips; Lipstick,0.000000,0,0,0,0,0,173
97833,MINI MULTI EYE COLOR PALETTE,80,Rp 423.000,Eyeshadow,Makeup; Eyes; Eyeshadow,4.883333,6,12,1,0,11,257
97801,FACE BLUSH,60,Rp 300.000,Blush,Makeup; Face; Blush,4.858824,13,17,2,0,15,387
...,...,...,...,...,...,...,...,...,...,...,...,...
2158,Ambre Noir Eau De Toilette,130,Rp 659.000,Eau De Toilette,Shop By Departments; Home; UOBMon,4.476190,7,6,1,2,4,355
64174,Soin Stimulating Conditioner,30,Rp 199.000,Conditioner,Hair Care; Shampoo; Conditioner,4.638889,9,7,1,2,6,122
36357,Repair Hair Mask,50,Rp 289.000,Hair Mask,Hair Care; Hair Treatment; Hair Mask,4.750000,5,5,1,0,4,58
36404,Hand Cream Olive Petitgrain,20,Rp 109.000,Hand & Foot Cream,Shop By Departments; Home; 12.12 PRICE POINT 50%,4.968750,8,8,2,0,6,117
64153,Color Mask,50,Rp 289.000,Hair Mask,Hair Care; Hair Treatment; Hair Mask,4.500000,2,2,1,0,1,35

In [26]:
# About tab
t10 = st.tab("About")
with t10:
    st.markdown("This is a simple Streamlit app about Product Catalogue")
    st.markdown("Built with love using Python and Streamlit.")

NameError: name 'st' is not defined

In [ ]:
with st.tabs(["Bivariate", "Trivariate", 'About']):
    with st.tab_item("About"):
        st.markdown("This is a simple Streamlit app about Product Catalogue")
        st.markdown("Built with love using Python and Streamlit.")

# Not Final

In [ ]:
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

# Configure the page
st.set_page_config(
    page_title="Sociolla Products Catalog",
    page_icon='🧿',
    layout="wide",
)

#1. Load the data
@st.cache_data()
def load_data():
    url = 'data/products_all_brands.csv'
    df = pd.read_csv(url)
    return df

# Build the UI
st.title("Sociolla Products Catalog")
st.header("Products Catalog Dataset")
with st.spinner("Loading data..."):
    df = load_data()

# Remove specific columns
columns_to_remove = ["url", "price_by_combinations", "active_date", "rating_types_str", "average_rating_by_types"]

# Check if the columns exist in the DataFrame before removing
columns_exist = all(column in df.columns for column in columns_to_remove)

if columns_exist:
    # Remove the specified columns
    df.drop(columns=columns_to_remove, inplace=True)
#    st.success(f"Columns {', '.join(columns_to_remove)} removed successfully.")
else:
    st.error("One or more columns do not exist in the DataFrame.")

# Display the updated DataFrame
st.dataframe(df, use_container_width=True)

#st.info("Raw data in DataFrame")
#st.dataframe(df.head(), use_container_width=True)

st.success("Column information of the dataset")
cols = df.columns.tolist()
st.subheader(f'Total columns {len(cols)} ➡ {", ".join(cols)}')

# Scatter plot section
st.header("Scatter Plot")
num_cols = df.select_dtypes(include=np.number).columns.tolist()

with st.expander("Customize Scatter Plot"):
    col1 = st.selectbox("Select the first column for scatter plot", num_cols)
    col2 = st.selectbox("Select the second column for scatter plot", num_cols)
    scatter_fig = px.scatter(df, x=col1, y=col2, title=f'{col1} vs {col2}')
    st.plotly_chart(scatter_fig, use_container_width=True)

# Additional Plots
st.header("Additional Visualizations")
gop = ['Bar', 'Pie', 'Histogram', 'Box', 'Violin',
        'Scatter', 'Area', 'Pair', 'Bubble',
        'Heatmap', 'Funnel', 'Treemap']

# Bar Plot
st.subheader("Bar Plot")
bar_col = st.selectbox("Select the column for bar plot", df.columns)
bar_fig = px.bar(df, x=bar_col, title=f'Bar Plot - {bar_col}')
st.plotly_chart(bar_fig, use_container_width=True)

# Pie Chart
st.subheader("Pie Chart")
pie_col = st.selectbox("Select the column for pie chart", df.columns)
pie_fig = px.pie(df, names=pie_col, title=f'Pie Chart - {pie_col}')
st.plotly_chart(pie_fig, use_container_width=True)

# Histogram
st.subheader("Histogram")
hist_col = st.selectbox("Select the column for histogram", num_cols)
hist_fig = px.histogram(df, x=hist_col, title=f'Histogram - {hist_col}')
st.plotly_chart(hist_fig, use_container_width=True)

# Box Plot
st.subheader("Box Plot")
box_col = st.selectbox("Select the column for box plot", num_cols)
box_fig = px.box(df, x=box_col, title=f'Box Plot - {box_col}')
st.plotly_chart(box_fig, use_container_width=True)

# Violin Plot
st.subheader("Violin Plot")
violin_col = st.selectbox("Select the column for violin plot", num_cols)
violin_fig = px.violin(df, y=violin_col, box=True, title=f'Violin Plot - {violin_col}')
st.plotly_chart(violin_fig, use_container_width=True)

# Scatter Matrix
st.subheader("Scatter Matrix")
scatter_matrix_fig = px.scatter_matrix(df, title='Scatter Matrix')
st.plotly_chart(scatter_matrix_fig, use_container_width=True)

# Area Plot
st.subheader("Area Plot")
area_col = st.selectbox("Select the column for area plot", num_cols)
area_fig = px.area(df, x=df.index, y=area_col, title=f'Area Plot - {area_col}')
st.plotly_chart(area_fig, use_container_width=True)

# Pair Plot
st.subheader("Pair Plot")
pair_plot_fig = px.scatter_matrix(df, title='Pair Plot')
st.plotly_chart(pair_plot_fig, use_container_width=True)

# Bubble Chart
st.subheader("Bubble Chart")
bubble_col1 = st.selectbox("Select the column for bubble chart (x-axis)", num_cols)
bubble_col2 = st.selectbox("Select the column for bubble chart (y-axis)", num_cols)
bubble_size_col = st.selectbox("Select the column for bubble size", num_cols)
bubble_fig = px.scatter(df, x=bubble_col1, y=bubble_col2, size=bubble_size_col, title='Bubble Chart')
st.plotly_chart(bubble_fig, use_container_width=True)

# Heatmap
st.subheader("Heatmap")
heatmap_cols = st.multiselect("Select columns for heatmap", num_cols)
heatmap_fig = px.imshow(df[heatmap_cols].corr(), labels=dict(color="Correlation"), title="Heatmap")
st.plotly_chart(heatmap_fig, use_container_width=True)

# Funnel Chart
st.subheader("Funnel Chart")
funnel_col = st.selectbox("Select the column for funnel chart", df.columns)
funnel_fig = px.funnel(df, x=funnel_col, title=f'Funnel Chart - {funnel_col}')
st.plotly_chart(funnel_fig, use_container_width=True)

# Treemap
st.subheader("Treemap")
treemap_cols = st.multiselect("Select columns for treemap", [funnel_col] + num_cols)
treemap_fig = px.treemap(df, path=treemap_cols, title="Treemap")
st.plotly_chart(treemap_fig, use_container_width=True)

st.success("Column information of the dataset")
cols = df.columns.tolist()

with st.tab_item("About"):
        st.markdown("This is a simple Streamlit app about Product Catalogue")
        st.markdown("Built with love using Python and Streamlit.")




# how to run the app 
# open terminal and run: 
# streamlit run main.py

# Final

In [ ]:
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt



# Configure the page
st.set_page_config(
    page_title="Sociolla Products Catalog",
    page_icon='🧿',
    layout="wide",
)

#1. Load the data
@st.cache_data
def load_data():
    url = 'data/products_all_brands.csv'
    df = pd.read_csv(url)
    return df

# Build the UI
st.title("Sociolla Products Catalog")
st.header("Products Catalog Dataset")
with st.spinner("Loading data..."):
    df = load_data()

# Remove specific columns
columns_to_remove = ["url", "price_by_combinations", "active_date", "rating_types_str", "average_rating_by_types"]

# Check if the columns exist in the DataFrame before removing
columns_exist = all(column in df.columns for column in columns_to_remove)

if columns_exist:
    # Remove the specified columns
    df.drop(columns=columns_to_remove, inplace=True)
else:
    st.error("One or more columns do not exist in the DataFrame.")

# Display the updated DataFrame
st.dataframe(df, use_container_width=True)

st.success("Column information of the dataset")
cols = df.columns.tolist()
st.subheader(f'Total columns {len(cols)} ➡ {", ".join(cols)}')

# Additional Plots
st.header("Additional Visualizations")

# Select box for the type of graph
selected_graph = st.selectbox("Select the type of graph", ['Bar', 'Pie', 'Histogram', 'Box', 'Violin',
                                                        'Scatter', 'Area', 'Pair', 'Bubble',
                                                        'Heatmap', 'Funnel', 'Treemap',
                                                        '3D Scatter Plot', '3D Line Plot', '3D Surface Plot'])

# Dynamically generate select box for column based on the selected graph type
selected_column = None

if selected_graph in ['Bar', 'Pie', 'Histogram', 'Box', 'Violin', 'Area', 'Funnel']:
    selected_column = st.selectbox(f"Select the column for {selected_graph} plot", df.columns)

elif selected_graph in ['Scatter', 'Bubble', 'Pair']:
    selected_column = st.selectbox(f"Select the column for {selected_graph} plot (x-axis)", df.columns)

elif selected_graph == 'Bubble':
    selected_column_size = st.selectbox("Select the column for bubble size", df.columns)

elif selected_graph == 'Heatmap':
    selected_columns_heatmap = st.multiselect("Select columns for heatmap", df.columns)

elif selected_graph == 'Treemap':
    # Assuming you want to choose a numerical column for treemap
    selected_columns_treemap = st.multiselect("Select columns for treemap", df.select_dtypes(include=np.number).columns.tolist())

# Plot based on the selected graph and column
if selected_graph == 'Bar':
    bar_fig = px.bar(df, x=selected_column, title=f'Bar Plot - {selected_column}')
    st.plotly_chart(bar_fig, use_container_width=True)

elif selected_graph == 'Pie':
    pie_fig = px.pie(df, names=selected_column, title=f'Pie Chart - {selected_column}')
    st.plotly_chart(pie_fig, use_container_width=True)

elif selected_graph == 'Histogram':
    hist_fig = px.histogram(df, x=selected_column, title=f'Histogram - {selected_column}')
    st.plotly_chart(hist_fig, use_container_width=True)

elif selected_graph == 'Treemap':
    treemap_fig = px.treemap(df, path=selected_columns_treemap, title="Treemap")
    st.plotly_chart(treemap_fig, use_container_width=True)

# 3D Plots
st.header("3D Visualizations")
selected_3d_graph = st.selectbox("Select the type of 3D graph", ['3D Scatter Plot', '3D Line Plot', '3D Surface Plot'])

if selected_3d_graph == '3D Scatter Plot':
    col1 = st.selectbox("Select the column for X-axis", df.columns)
    col2 = st.selectbox("Select the column for Y-axis", df.columns)
    col3 = st.selectbox("Select the column for Z-axis", df.columns)
    fig_3d_scatter = px.scatter_3d(df, x=col1, y=col2, z=col3, title=f'3D Scatter Plot - {col1} vs {col2} vs {col3}')
    st.plotly_chart(fig_3d_scatter, use_container_width=True)

elif selected_3d_graph == '3D Line Plot':
    col1 = st.selectbox("Select the column for X-axis", df.columns)
    col2 = st.selectbox("Select the column for Y-axis", df.columns)
    col3 = st.selectbox("Select the column for Z-axis", df.columns)
    fig_3d_line = px.line_3d(df, x=col1, y=col2, z=col3, title=f'3D Line Plot - {col1} vs {col2} vs {col3}')
    st.plotly_chart(fig_3d_line, use_container_width=True)

elif selected_3d_graph == '3D Surface Plot':
    col1 = st.selectbox("Select the column for X-axis", df.columns)
    col2 = st.selectbox("Select the column for Y-axis", df.columns)
    col3 = st.selectbox("Select the column for Z-axis", df.columns)
    fig_3d_surface = px.surface(df, x=col1, y=col2, z=col3, title=f'3D Surface Plot - {col1} vs {col2} vs {col3}')
    st.plotly_chart(fig_3d_surface, use_container_width=True)